/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.7 */
/* Mon Dec  2 09:33:32 2019 */

/* parameterized module instance */
my_pll __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
