[ActiveSupport PAR]
; Global primary clocks
GLOBAL_PRIMARY_USED = 2;
; Global primary clock #0
GLOBAL_PRIMARY_0_SIGNALNAME = clk_out_1_pre;
GLOBAL_PRIMARY_0_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_0_LOADNUM = 17;
; Global primary clock #1
GLOBAL_PRIMARY_1_SIGNALNAME = clk_out_2_pre;
GLOBAL_PRIMARY_1_DRIVERTYPE = PLL;
GLOBAL_PRIMARY_1_LOADNUM = 159;
; # of global secondary clocks
GLOBAL_SECONDARY_USED = 4;
; Global secondary clock #0
GLOBAL_SECONDARY_0_SIGNALNAME = clk_div_inst_2/n181;
GLOBAL_SECONDARY_0_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_0_LOADNUM = 17;
GLOBAL_SECONDARY_0_SIGTYPE = RST;
; Global secondary clock #1
GLOBAL_SECONDARY_1_SIGNALNAME = reset_n_c;
GLOBAL_SECONDARY_1_DRIVERTYPE = PIO;
GLOBAL_SECONDARY_1_LOADNUM = 145;
GLOBAL_SECONDARY_1_SIGTYPE = RST;
; Global secondary clock #2
GLOBAL_SECONDARY_2_SIGNALNAME = RD_EN;
GLOBAL_SECONDARY_2_DRIVERTYPE = PIO;
GLOBAL_SECONDARY_2_LOADNUM = 16;
GLOBAL_SECONDARY_2_SIGTYPE = CE;
; Global secondary clock #3
GLOBAL_SECONDARY_3_SIGNALNAME = clk_div_inst_1/n178;
GLOBAL_SECONDARY_3_DRIVERTYPE = SLICE;
GLOBAL_SECONDARY_3_LOADNUM = 17;
GLOBAL_SECONDARY_3_SIGTYPE = RST;
; I/O Bank 0 Usage
BANK_0_USED = 2;
BANK_0_AVAIL = 26;
BANK_0_VCCIO = 3.3V;
BANK_0_VREF1 = NA;
; I/O Bank 1 Usage
BANK_1_USED = 9;
BANK_1_AVAIL = 26;
BANK_1_VCCIO = 3.3V;
BANK_1_VREF1 = NA;
; I/O Bank 2 Usage
BANK_2_USED = 12;
BANK_2_AVAIL = 28;
BANK_2_VCCIO = 3.3V;
BANK_2_VREF1 = NA;
; I/O Bank 3 Usage
BANK_3_USED = 4;
BANK_3_AVAIL = 7;
BANK_3_VCCIO = 3.3V;
BANK_3_VREF1 = NA;
; I/O Bank 4 Usage
BANK_4_USED = 4;
BANK_4_AVAIL = 8;
BANK_4_VCCIO = 3.3V;
BANK_4_VREF1 = NA;
; I/O Bank 5 Usage
BANK_5_USED = 2;
BANK_5_AVAIL = 10;
BANK_5_VCCIO = 3.3V;
BANK_5_VREF1 = NA;
